### ISSUE TITLE
Webpack and request module

### ISSUE THREAD

**Issue by pltod** [webpack/react-starter#3]
Great configurations shown in this project! 

I have one question regarding consumption of https://github.com/mikeal/request.
When using webpack with application that uses request module I am getting something like:

ERROR in ./~/request/request.js
Module not found: Error: Cannot resolve module 'net' in 
@ ./~/request/request.js 32:10-24

ERROR in ./~/request/~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in 
@ ./~/request/~/forever-agent/index.js 7:10-24

Is there a way to make webpack and request working together ?

**Comment by lai32290** [comment]
This is help for me! Thanks for you

**Comment by nrempel** [comment]
@sokra 

```
{
  "browser": {
    "net": false,
    "tls": false
  }
}
```

Does not seem to be a part of the package.json spec. I can't see any documentation here https://docs.npmjs.com/files/package.json.

Is this is a convention that webpack uses?

Thanks.

**Edit:

Is it related to this spec? https://github.com/defunctzombie/package-browser-field-spec

**Comment by thg303** [comment]
any practical solution for this issue? or I have to push the 'eject' and leave the starter?
