### ISSUE TITLE
where are the entries for hot module reload

### ISSUE THREAD

**Issue by bsr203** [webpack/react-starter#32]
Hello,
@gaearon was helping me to understand why hot reload doesn't work with gulp. I use this repo, and just trying to combine with other gulp task. The gulpfile is below.

@gaearon
```
Maybe you’re missing webpack-dev-server/client or webpack/hot/only-dev-server in entry
 I don’t really understand where it’s in react-starter but hot reload can’t work without these two servers
```
I too couldn't see any refrence to hot reload related entries, except one for the app `https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L9`. Can you please help us to understand.

----
from the discussion at
https://gitter.im/webpack/webpack
https://gitter.im/gaearon/react-hot-loader

-----
Hello,
I am using react-starter from webpack repo, and everything works including hot reload with the default command

npm run hot-dev-server ("webpack-dev-server --config webpack-hot-dev-server.config.js --hot --progress --colors --port 2992 --inline")

I am trying to extract this to gulp so that I can combine with other tasks. The implementation is

```
var gulp = require('gulp');
var webpack = require('webpack');
var WebpackDevServer = require("webpack-dev-server");
var $ = require('gulp-load-plugins')();

function wpkServer(wpkConf, srvConf, cb) {
    var compiler = webpack(wpkConf);
    new WebpackDevServer(compiler, srvConf).listen(srvConf.port, "localhost", function (err) {
        if (err) throw new $.util.PluginError("webpack-dev-server", err);
        // Server listening
        $.util.log("[webpack-dev-server]", "http://localhost:8080");
        // keep the server alive or continue?
        cb();
    });
}
gulp.task("webpack-hot-dev-server", function (cb) {
    var wpkConf =  require("./webpack-hot-dev-server.config.js");
    wpkServer(wpkConf,
        { // server and middleware options
            publicPath: wpkConf.output.publicPath,
            hot: true,
            port: 2992,
            stats: { colors: true }
        },
        cb)
});
hot realod stop working, but if I refresh I could see the changes. What is wrong.
I used different ports for listen, but only 2992 works (in examples I see it is different like 8080, 3000)

so what is the above gulp config different from

webpack-dev-server --config webpack-hot-dev-server.config.js --hot --progress --colors --port 2992 --inline"
which works !!!
```

**Comment by sokra** [comment]
The  `--inline` flag does the magic. It adds the `webpack-dev-server/client` and in hot mode also the `webpack/hot/dev-server` entry point.

... It used to be in the documentation, but somebody removed it... :cry:

**Comment by bsr203** [comment]
thanks. I saw it here https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L105

but not sure how it escaped a search in the repo.

thanks a ton for webpack, as I am just exploring, and amazing the productivity it brings ... cheers.

**Comment by bsr203** [comment]
Hi, I may close it after your confirmation.

Do you thinl options allowed though the command line as in the [cli](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js),  could also be allowed through the [lib](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js)?

**Comment by bsr203** [comment]
nevermind. It may better I just start it from terminal without gulp. If I ever needed, I may alter config as you do in the cli binary. thanks.
