### ISSUE TITLE
Example of using images

### ISSUE THREAD

**Issue by jonaswindey** [webpack/react-starter#41]
I'm trying to load an image from my /public folder using the image-loader.

What's the best way to get the path in my components? In dev mode, the publicPath is different than on production mode.

**Comment by sokra** [comment]
Images shouldn't be in the `/public` folder... Just put them into the app folder side-by-side with your scripts. Than require them... They are [configured](https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L22) to be copied to the output directory and the url is exported.

**Comment by jonaswindey** [comment]
Great, that's awesome. So what is the general use of the /public folder?

**Comment by sokra** [comment]
https://github.com/webpack/react-starter#legacy-static-assets

**Comment by jonaswindey** [comment]
Yes I saw, but what type of content should be served from there? And how do I get the public url for each environment?

**Comment by sokra** [comment]
Only stuff that doesn't work with webpack or are not ported over yet. They are served [from `/`](https://github.com/webpack/react-starter/blob/master/lib/server.js#L29-L30).

The public path for the webpack served assets is accessable with `__webpack_public_path__`.

**Comment by jonaswindey** [comment]
Thanks.
