### ISSUE TITLE
Default build broken (dev and prod)

### ISSUE THREAD

**Issue by pikeas** [webpack/react-starter#43]
Steps to reproduce:

    hub clone webpack/react-starter test
    cd test
    
    # dev
    npm run dev-server
    npm run start-dev (in new window)

    # or prod
    npm run build
    npm run start

Testing in both Chrome and Firefox, localhost:8080 displays a page that says "react-starter", and a button labeled "Update data". There is no other page content, and clicking the button does nothing.

**Comment by ZucchiniZe** [comment]
This is also happening to me. When I looked into the react source with the chrome extension, inside the `RouteHandler` component it is rendering a noscript tag.

**Comment by jonaswindey** [comment]
It's linked to react-router. I have tried downgrading to "0.12.0" and then it's working again. "^0.12.0" will install "0.12.2" which breaks the functionality.
