### ISSUE TITLE
Use babel-loader instead of jsx-loader

### ISSUE THREAD

**Issue by gaearon** [webpack/react-starter#48]
I think it would be nice to switch to Babel instead of jsx-loader as it's got better ES6 support.

**Comment by MuhammadMuneer** [comment]
@gaearon You can enable ES6 support with jsx-loader by appending ?harmony and you can see that in the config file.

**Comment by gaearon** [comment]
I can, but it supports a lot less ES6 than Babel. See http://kangax.github.io/compat-table/es6/

**Comment by FoxxMD** [comment]
:+1:

**Comment by sokra** [comment]
:+1:

**Comment by Rockfordal** [comment]
babel works great for me, i excluded node_modules.
(im using reflux, material-ui, socket.io). tnx for a superb starter!

**Comment by FoxxMD** [comment]
@Rockfordal how did you switch? I've added babel to additional loaders in webpack and concatenated these to the final loaders but it doesn't seem to be working
```
	var additionalLoaders = [
		{ test: /\.js$/, include: /react-typeahead/, exclude: /node_modules/, loader: "babel-loader" },
        { test: /\.jsx$/, exclude: /node_modules/, loader: options.hotComponents ? ["react-hot-loader", "babel-loader"] : "babel-loader" }
	];
```

I get a module parsing failure on app.jsx in config :/

**Comment by sokra** [comment]
You need to change these lines:

* https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L14
* https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L16-L19

Someone like to do a PR?

**Comment by sokra** [comment]
As next step we can change the module style to ES6 modules.

**Comment by FoxxMD** [comment]
@sokra Doesn't using `loadersByExtension` preclude the possibility of writing your own tests and excludes for any loaders? If I wanted to write my files as normal `.js` and use `babel-loader` I wouldn't be able to exclude `node_modules`, or am I overlooking some functionality in `loadersByExtension` that allows this?

Also, If I am using `additionalLoaders` and concat them why would they not be be working? I have commented out the extension loader for `jsx` and my additionalLoaders look like this:
```
	var additionalLoaders = [
		{ test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" }//,
        { test: /\.jsx$/, exclude: /node_modules/, loader: options.hotComponents ? ["react-hot-loader", "babel-loader"] : "babel-loader" }
	];
```

**Comment by sokra** [comment]
Should also work.
But you can specify `exluce` and `include` in `loadersByExtension`. See https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L16-L19

**Comment by FoxxMD** [comment]
That worked! So what is loadersByExtension doing that concatenating additionalLoaders is not?

**Comment by pikeas** [comment]
@FoxxMD https://github.com/webpack/react-starter/issues/42

**Comment by sokra** [comment]
#60
