### ISSUE TITLE
items-store outdated?

### ISSUE THREAD

**Issue by Frikki** [webpack/react-starter#65]
I noticed that the items-store used is v0.4.2, whereas the current is v0.6.1 that doesn’t have the `StateFromStoresMixin` but has replaced it with a `createContainer` wrapper method.

Currently, the application uses the mixin, but to my knowledge, this is considered bad practice. Are there any plans on changing this? What if I’d like to transition away from the mixin myself, how is that possible?

**Comment by sokra** [comment]
Check the latest version of react-starter which uses ES6 classes and no mixins.

**Comment by Frikki** [comment]
Great! I must have missed that update. It works painlessly, and the architecture is becoming much clearer.
