### ISSUE TITLE
Error parsing ES6 variables (...other) during development, for examples in React V0.13.x 

### ISSUE THREAD

**Issue by codeuniquely** [webpack/react-starter#68]
There are a number of occasions when you want to pass the remaining properties into an object rather than explicitly defining them all all the time ...

Quoting from react: https://facebook.github.io/react/docs/transferring-props.html

"Sometimes it's fragile and tedious to pass every property along. In that case you can use destructuring assignment with rest properties to extract a set of unknown properties.
List out all the properties that you would like to consume, followed by ...other."

i.e.

    var { checked, ...other } = this.props;

So when you do this WebPack / Babel / rebuild fails to parse the code change and you get a 

```
 Unexpected token (16:17)

 render() {
         var { checked, ...other } = this.props;
                        ^
         return <div className={loading ? "application loading" : "app

**Comment by barrystaes** [comment]
For posterity - if anyone is getting "Unexpected token" on their `createMessage` implementation, this should fix it.
