### ISSUE TITLE
prerendered placeholder styles

### ISSUE THREAD

**Issue by Coobaha** [webpack/react-starter#69]
Hi @sokra !

https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L110

Here in config styles loader is replaced with null-loader, so in pre-rendered server markup css placeholders are undefined, but on client side after load they will get their class names. This will cause page repaint after getting new classes

and also you will get  warnings from react (if react env isnt production ofc)
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div class="z53edca59e642b4b8502
 (server) <div class="undefined" data-reac
```

**Comment by sokra** [comment]
You are right... I didn't considered this.

**Comment by Coobaha** [comment]
i think good way to handle this is to have something like css-loader?placeholders-only option

**Comment by sokra** [comment]
yup... working on that..

**Comment by Coobaha** [comment]
:+1:

**Comment by Coobaha** [comment]
but..
now there is still an issue
they are not shared
```
(client) <div class="z53edca59e642b4b85028
(server) <div class=“zacbbe33f8c1d8ad03f79
```

**Comment by sokra** [comment]
The syntax changed a bit to make more sense and to support `less` `sass` `stylus` etc:

``` css
.local[className] {
  background: red;
}
```

``` js
import style from "./style.css";

// i. e. react.js
return <div className={style.className}>Text</div>;
```
