### ISSUE TITLE
this.state is null inside render() ?

### ISSUE THREAD

**Issue by barrystaes** [webpack/react-starter#77]
Using the latest version for some reason `this.state==null` in `render()` and i dont understand why.

**Comment by sokra** [comment]
`this.state` isn't used. `null` is the default value. Why is this an issue?

**Comment by barrystaes** [comment]
Sorry, i forgot to set state. ([i updated my demo branch](https://github.com/barrystaes/react-starter/tree/demo-issue77))

This works:
```
componentDidMount() {
  this.setState({foo: "works"});
}
```
My issue is that setting initial state "the normal way" no longer works: 
```
static getInitialState() {
  return {demo: "Hello #77"}
}
```
Did this change in React 0.13 perhaps? I could not find anything on that in [API](https://facebook.github.io/react/docs/component-api.html) or [specs](https://facebook.github.io/react/docs/component-specs.html#getinitialstate) docs.

On a related note; `getInitialState()` is not called when using `renderToString()` but i am not using prerender.

**Comment by barrystaes** [comment]
Ah now i get this.. (no idea why i have not seen this before!)
```
Warning: getInitialState was defined on SomePage, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
```
And indeed, i am not using `React.createClass` but 
```
export default class SomePage extends React.Component {
```
And i was thinking this did the same thing, but apparently not.. insights welcome.

**Comment by barrystaes** [comment]
Am i supposed to do this?
```
constructor(props) {
  setState({foo: "bar"});
}
```

**Comment by sokra** [comment]
``` js
constructor(props) {
  super(props);
  this.state = { foo: "bar" };
}
```

**Comment by barrystaes** [comment]
Thanks @sokra !
Seems there are more differences with regard to `React.Component` (React 0.13) than i realized.

If this is documented somewhere, i'd be happy to learn where. The only thing i found that mentioned such a thing was a [coffeescript example](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html).

**Comment by AlastairTaft** [comment]
Instead of doing it in the constructor this seems to work for me

```
class MyComponent extends Component {
  state = {
    foo: "bar"
  }
...
```

**Comment by EugeneZ** [comment]
@AlastairTaft That only works if you are using the [proposed ECMAScript class fields syntax](https://github.com/jeffmo/es-class-fields-and-static-properties). For example by installing the [relevant Babel plugin](http://babeljs.io/docs/plugins/transform-class-properties/).

**Comment by ibrahima** [comment]
@barrystaes thanks for that link, wish that was documented more prominently somewhere. I think it's a reasonable change but I wasn't expecting it from reading the tutorials that mention ES6 class syntax.

**Comment by thebadasscoder** [comment]
Make sure getInitialState is spelled correctly which was causing me to have that error. -__-  Just take your time coding.

**Comment by sojelee** [comment]
@twilsonpierce awsome was getting same error, I mispelled getInitialState
