### ISSUE TITLE
Port issue on Azure

### ISSUE THREAD

**Issue by Cellule** [webpack/react-starter#78]
I tried to deploy my web application on Azure today and after hours of searching I came to realize that the problem I had was with the port.

Basically, in https://github.com/webpack/react-starter/blob/master/lib/server.js#L69 there's `+(process.env.PORT || options.defaultPort || 8080);` where we cast all these values to a number.

The problem is that in Azure, the port is provided through `process.env.PORT` and is not a number. It's something like "\\.\pipe\somehash". I don't remember the exact syntax but it look like that.

The solution I found, was obviously to remove the cast to a number.
Also, if we look at https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback we can see `To listen to a unix socket, supply a filename instead of port and hostname.` which means, the port can be a path instead of a number.

Therefore, I think it's fair to remove the cast and avoid these kind of headaches to others :)

**Comment by sokra** [comment]
Please send a PR.

Take care that you should still be able to provide a port number as string (`PORT=80 ...`). Removing the `+` is not enough.

**Comment by Cellule** [comment]
I just tested and listen seems to take care of that. I tried changing the `defaultPort` to `"8080"` and it still work perfectly. Apparently, there is no need for the port to be a number.
