### ISSUE TITLE
Error defining includePaths for sass-loader

### ISSUE THREAD

**Issue by borillo** [webpack/react-starter#85]
Hi guys,

Thanks for sucha a great starter :)

I'm trying to add includePaths[]=./node_modules/zurb-foundation-5/scss/ in the definition of the sass-loader:

    var stylesheetLoaders = {
    	"css": cssLoader,
    	"less": [cssLoader, "less-loader"],
    	"styl": [cssLoader, "stylus-loader"],
    	"scss|sass": [cssLoader, "sass-loader?includePaths[]=./node_modules/zurb-foundation-5/scss/"]
    };

But webpack crash with this error:
60% 236/278 build modulesBus error: 10

Any clues?

Thanks in advance

**Comment by sokra** [comment]
report it to the sass-loader.
