### ISSUE TITLE
Request: a way to use the production React build with this

### ISSUE THREAD

**Issue by jedwards1211** [webpack/react-starter#88]
Unless I misunderstand, I haven't seen a Webpack config yet that uses the production React build in production.  They all seem to get it from the npm package, which still prints warnings, checks `PropTypes`, etc.  I'm trying to figure out if it's possible to configure Webpack so that I can `require()` React from this pre-bundled production build, so if you have any idea, would you mind letting me know?

**Comment by cesarandreu** [comment]
When you generate a production build you should be using webpack.DefinePlugin, and passing it `{ 'process.env.NODE_ENV': '"production"' }`. That'll cause the conditional `process.env.NODE_ENV !== "production"` to becomes `"production" !== "production"`, so uglifyjs will do dead code elimination and remove all the prop checks and warnings.

**Comment by jedwards1211** [comment]
Oh, okay, cool!  I had tried running webpack with the `env` command, but the output bundle was no smaller than before.  Or maybe I don't have UglifyJS configured.  But I wasn't aware of the DefinePlugin, that's good to know.  Thanks!
