### ISSUE TITLE
How to exclude files from prerender?

### ISSUE THREAD

**Issue by raptoria** [webpack/react-starter#90]
Plz excuse my n00bness..
I added some authentication on top of your boilerplate, and naturally, when I run "npm run start" , this line of code fails during the prerender.

/home/clacey/react-flask/build/prerender/main.js:224
		var jwt = localStorage.getItem('jwt');
		          ^
ReferenceError: localStorage is not defined

It makes sense that there is no localStorage.. i've included a
 if (canUseDOM){
	let jwt = localStorage.getItem('jwt');

in my code to protect it, but it still enters the if loop..not sure the best way of doing this - or if i'm violating some sort of pre-render rule to begin with.

Any help would be greatly appreciated!

**Comment by josephfinlayson** [comment]
`if (window) ` should do it

**Comment by raptoria** [comment]
ah thanks for the hint..the problem was with how I was importing and using canUseDom.

This fixed it:
import ExecutionEnvironment from "react/lib/ExecutionEnvironment";
if (ExecutionEnvironment.canUseDOM)
